[mikan]
rss = "https://mikanani.me/RSS/MyBangumi?token=token"
interval = 500
proxy = "http://localhost:7890"

[byrbt]
# support multiple rss-es.
rsses = ["https://byr.pt/torrentrss.php?passkey=xxx", "https://byr.pt/torrentrss.php?passkey=xxx"]
interval = 500

[tjupt]
# support multiple rss-es.
rsses = ["https://www.tjupt.org/torrentrss.php?rows=10&cat402=1&icat=1&ismalldescr=1&isize=1&iuplder=1&passkey="]
interval = 500

[cqhttp]
name = "BOT"
uin = "123456789"
api = "http://localhost:8000"
dms = [114514, 1919810]
groups = [114514, 1919810]
delay = 200
with_torrent = true

[qq]
app_id = "app id"
app_secret = "app secret"
channel_id = "channel id"
sandbox = true