name: "Check License Lines"
on: [push, pull_request]
jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: License Checker
        uses: kt3k/license_checker@v1.0.6