name: "Check clippy and toml"
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true

      - name: Check clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          
      - name: Check toml 
        run: |
          wget https://github.com/tamasfe/taplo/releases/download/0.8.0/taplo-linux-x86_64.gz
          gunzip taplo-linux-x86_64.gz
          chmod +x taplo-linux-x86_64
          ./taplo-linux-x86_64 fmt --check

  